### ISSUE TITLE
cProfile doesn't seem to work in Anaconda + Python3

### ISSUE THREAD

**Issue by harrison-caudill** [harrison-caudill/pylink#31]
```
(dev) kungfoo@tatyana ~/dev/pylink/examples $ python profile.py 

Traceback (most recent call last):
  File "profile.py", line 3, in <module>
    import cProfile
  File "/Users/kungfoo/.conda/anaconda2/envs/dev/lib/python3.7/cProfile.py", line 22, in <module>
    run.__doc__ = _pyprofile.run.__doc__
AttributeError: module 'profile' has no attribute 'run'
(dev) kungfoo@tatyana ~/dev/pylink/examples $ 
```

**Comment by harrison-caudill** [comment]
fixed in v0.4
